In [1]:
import pandas as pd
import numpy as np

In [8]:
# Use tabula to read pdf files.
# http://tabula.technology/

# Upload converted csv file.
queretaro = pd.read_csv('queretaro_tabula_2017.csv')

# Select entries referring to taxis.
queretaro = queretaro[queretaro['Modalidad'] == 'TAXI'] 

# Create an ID column.
#queretaro['id'] = queretaro.index 
#queretaro.id += 1

#queretaro.index = np.arange(0, len(queretaro))
#queretaro['id'] = queretaro.index
#queretaro.id += 1

queretaro = queretaro.reset_index()



# Delete unnecessary columns.
del queretaro['Modalidad']
del queretaro['NO\rCONSEC.']

# Rename columns.
queretaro.columns = ['id', 'concesion', 'nueva_concesion', 'zona', 'municipio', 'nombre', 'ultima_referencia']

# Reorder columns.
queretaro = queretaro[['id', 'nombre', 'municipio', 'zona', 'concesion', 'nueva_concesion', 'ultima_referencia']]

# Fill missing values.
#queretaro.nombre = queretaro.nombre.fillna('NA')
#queretaro.municipio = queretaro.municipio.fillna('NA')
#queretaro.zona = queretaro.zona.fillna('NA')
#queretaro.nueva_concesion = queretaro.nueva_concesion.fillna('NA')
#queretaro.ultima_referencia = queretaro.ultima_referencia.fillna(0)

# Convert data types.
#queretaro.concesion = queretaro.concesion.astype(int)
#queretaro.ultima_referencia = queretaro.ultima_referencia.astype(int)
#queretaro.ultima_referencia = pd.to_datetime(queretaro.ultima_referencia, format = '%Y', errors = 'coerce')


# Convert text values to lower case.
#queretaro.nombre = queretaro.nombre.str.lower()
#queretaro.municipio = queretaro.municipio.str.lower()
#queretaro.zona = queretaro.zona.str.lower()

# Remove carriage returns.
#queretaro.nombre = queretaro.nombre.str.replace(r'\r', ' ')
#queretaro.nombre = queretaro.nombre.str.replace(r'\|\|', '-')

In [9]:
queretaro.head()

,id,nombre,municipio,zona,concesion,nueva_concesion,ultima_referencia
0,0,ROSA MA. OBREGON ZEPEDA ||\rFEDERACION DE TRAB...,AMEALCO,URBANO,238.0,TA-0035,2016.0
1,1,MA. ANTONIA RUIZ VEGA,AMEALCO,URBANO,250.0,TA-0034,2016.0
2,2,GASPAR FEREGRINO CUELLAR,AMEALCO,URBANO,378.0,TA-0058,2016.0
3,3,CARLOS PEREZ UGALDE,AMEALCO,URBANO,398.0,TA-0018,2016.0
4,4,JOSE ESAU DURAN GARDUÑO,AMEALCO,URBANO,547.0,TA-0070,2016.0

In [10]:
queretaro[100:120]

,id,nombre,municipio,zona,concesion,nueva_concesion,ultima_referencia
100,100,LORENA DEL ROCIO GALVAN SANTOS,AMEALCO,URBANO,6030.0,TA-6030,2016.0
101,101,YOLANDA JURADO ALCANTAR,AMEALCO,URBANO,6031.0,TA-6031,2016.0
102,189,JUAN LUIS MARTINEZ ROMERO || OLAYA\rJASSO RAMIREZ,ARROYO SECO,SUBURBANO,3013.0,TSY-024,2016.0
103,190,DOMINGO NIETO MENDEZ,ARROYO SECO,SUBURBANO,4562.0,TSY-008,2016.0
104,191,APOLINAR BALDERAS LOPEZ || ARISTEA\rHERNANDEZ ...,ARROYO SECO,SUBURBANO,4586.0,TSY-015,2016.0
105,192,EULALIA MARTINEZ GUERRERO || TOMASA\rAGUADO MA...,ARROYO SECO,SUBURBANO,4587.0,TSY-016,2016.0
106,193,NICANOR MARTINEZ VEGA,ARROYO SECO,SUBURBANO,4598.0,TSY-009,2016.0
107,194,MARIA DEL ROCIO SANCHEZ VELAZQUEZ,ARROYO SECO,SUBURBANO,4603.0,TSY-023,2016.0
108,195,UNIDAD CÍVICA NACIONAL DEL SECTOR\rSOCIAL CARR...,ARROYO SECO,URBANO,4622.0,TY-0004,2015.0
109,196,RAFAEL CRUZ OLVERA,ARROYO SECO,SUBURBANO,4643.0,TSY-017,2016.0
110,197,SALOMON AGUADO LARA,ARROYO SECO,SUBURBANO,4653.0,TSY-025,2016.0
111,198,AIDA TREJO PRADO || ROMAN GONZALEZ\rIZQUIERDO,ARROYO SECO,SUBURBANO,4660.0,TSY-018,2016.0
112,199,MA. JANETH CASTILLO TORRES,ARROYO SECO,SUBURBANO,4673.0,TSY-019,2016.0
113,200,NORA ILDA CASTILLO TORRES,ARROYO SECO,URBANO,4675.0,TY-0001,2016.0
114,201,EDUARDO GARCIA RENDON,ARROYO SECO,SUBURBANO,4677.0,TSY-007,2016.0
115,202,MELANEA MENDOZA ZEPEDA,ARROYO SECO,SUBURBANO,4678.0,TSY-006,2016.0
116,203,OLIMPIA MARTINEZ JASSO,ARROYO SECO,SUBURBANO,4683.0,TSY-027,2016.0
117,204,ISIDORA BALDERAS VARGAS || ROBERTO\rRODRIGUEZ ...,ARROYO SECO,URBANO,4685.0,TY-0009,2014.0
118,205,PUEBLITO ELIAS BALDERAS LOYOLA,ARROYO SECO,SUBURBANO,4687.0,TSY-026,2016.0
119,206,GERARDO CRUZ OLVERA,ARROYO SECO,SUBURBANO,4688.0,TSY-014,2016.0